// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5194/' | (string & {});
};

export type AccessTokenResponse = {
    tokenType?: null | string;
    accessToken: string;
    expiresIn: number | string;
    refreshToken: string;
};

export type ChannelDto = {
    id?: null | string;
    name: string;
    groupId: string;
    createdBy?: null | string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type GroupDto = {
    id?: null | string;
    name: string;
    createdOn?: string;
    channels?: null | Array<string>;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type InfoRequest = {
    newEmail?: null | string;
    newPassword?: null | string;
    oldPassword?: null | string;
};

export type InfoResponse = {
    email: string;
    isEmailConfirmed: boolean;
};

export type LoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: null | string;
    twoFactorRecoveryCode?: null | string;
};

export type MessageDto = {
    id?: null | string;
    currentText: string;
    authorId?: null | string;
    createdOn?: null | string;
    lastEditedOn?: null | string;
    hasBeenEdited?: null | boolean;
    isDeleted?: null | boolean;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type ResendConfirmationEmailRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    email: string;
    resetCode: string;
    newPassword: string;
};

export type TwoFactorRequest = {
    enable?: null | boolean;
    twoFactorCode?: null | string;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: string;
    recoveryCodesLeft: number | string;
    recoveryCodes?: null | Array<string>;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type PostRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/login';
};

export type PostLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type MapIdentityApiConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        code: string;
        changedEmail?: string;
    };
    url: '/confirmEmail';
};

export type MapIdentityApiConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/resendConfirmationEmail';
};

export type PostResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/forgotPassword';
};

export type PostForgotPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostForgotPasswordError = PostForgotPasswordErrors[keyof PostForgotPasswordErrors];

export type PostForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/resetPassword';
};

export type PostResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostResetPasswordError = PostResetPasswordErrors[keyof PostResetPasswordErrors];

export type PostResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/manage/2fa';
};

export type PostManage2FaErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManage2FaError = PostManage2FaErrors[keyof PostManage2FaErrors];

export type PostManage2FaResponses = {
    /**
     * OK
     */
    200: TwoFactorResponse;
};

export type PostManage2FaResponse = PostManage2FaResponses[keyof PostManage2FaResponses];

export type GetManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type GetManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetManageInfoError = GetManageInfoErrors[keyof GetManageInfoErrors];

export type GetManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type GetManageInfoResponse = GetManageInfoResponses[keyof GetManageInfoResponses];

export type PostManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type PostManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManageInfoError = PostManageInfoErrors[keyof PostManageInfoErrors];

export type PostManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type PostManageInfoResponse = PostManageInfoResponses[keyof PostManageInfoResponses];

export type PostApiV1ChannelData = {
    body: ChannelDto;
    path?: never;
    query?: never;
    url: '/api/v1/Channel';
};

export type PostApiV1ChannelResponses = {
    /**
     * OK
     */
    200: ChannelDto;
};

export type PostApiV1ChannelResponse = PostApiV1ChannelResponses[keyof PostApiV1ChannelResponses];

export type PutApiV1ChannelData = {
    body: ChannelDto;
    path?: never;
    query?: never;
    url: '/api/v1/Channel';
};

export type PutApiV1ChannelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ChannelByIdMessagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        Take?: number | string;
        LastMessageId?: string;
    };
    url: '/api/v1/Channel/{id}/messages';
};

export type GetApiV1ChannelByIdMessagesResponses = {
    /**
     * OK
     */
    200: Array<MessageDto>;
};

export type GetApiV1ChannelByIdMessagesResponse = GetApiV1ChannelByIdMessagesResponses[keyof GetApiV1ChannelByIdMessagesResponses];

export type PostApiV1ChannelByIdMessageData = {
    body: string;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}/message';
};

export type PostApiV1ChannelByIdMessageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1ChannelByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}';
};

export type DeleteApiV1ChannelByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ChannelByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}';
};

export type GetApiV1ChannelByIdResponses = {
    /**
     * OK
     */
    200: ChannelDto;
};

export type GetApiV1ChannelByIdResponse = GetApiV1ChannelByIdResponses[keyof GetApiV1ChannelByIdResponses];

export type GetApiV1GroupByIdChannelsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}/channels';
};

export type GetApiV1GroupByIdChannelsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1GroupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type GetApiV1GroupResponses = {
    /**
     * OK
     */
    200: Array<GroupDto>;
};

export type GetApiV1GroupResponse = GetApiV1GroupResponses[keyof GetApiV1GroupResponses];

export type PostApiV1GroupData = {
    body: GroupDto;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type PostApiV1GroupResponses = {
    /**
     * OK
     */
    200: GroupDto;
};

export type PostApiV1GroupResponse = PostApiV1GroupResponses[keyof PostApiV1GroupResponses];

export type PutApiV1GroupData = {
    body: GroupDto;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type PutApiV1GroupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1GroupByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}';
};

export type DeleteApiV1GroupByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1GroupByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}';
};

export type GetApiV1GroupByIdResponses = {
    /**
     * OK
     */
    200: GroupDto;
};

export type GetApiV1GroupByIdResponse = GetApiV1GroupByIdResponses[keyof GetApiV1GroupByIdResponses];

export type PostApiV1MessageData = {
    body: MessageDto;
    path?: never;
    query?: never;
    url: '/api/v1/Message';
};

export type PostApiV1MessageResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type PostApiV1MessageResponse = PostApiV1MessageResponses[keyof PostApiV1MessageResponses];

export type PutApiV1MessageData = {
    body: MessageDto;
    path?: never;
    query?: never;
    url: '/api/v1/Message';
};

export type PutApiV1MessageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1MessageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Message/{id}';
};

export type DeleteApiV1MessageByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1MessageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Message/{id}';
};

export type GetApiV1MessageByIdResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type GetApiV1MessageByIdResponse = GetApiV1MessageByIdResponses[keyof GetApiV1MessageByIdResponses];
