// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiV1ChannelByIdData, DeleteApiV1ChannelByIdResponses, DeleteApiV1GroupByIdData, DeleteApiV1GroupByIdResponses, DeleteApiV1MessageByIdData, DeleteApiV1MessageByIdResponses, GetApiV1ChannelByIdData, GetApiV1ChannelByIdMessagesData, GetApiV1ChannelByIdMessagesResponses, GetApiV1ChannelByIdResponses, GetApiV1GroupByIdChannelsData, GetApiV1GroupByIdChannelsResponses, GetApiV1GroupByIdData, GetApiV1GroupByIdResponses, GetApiV1GroupData, GetApiV1GroupResponses, GetApiV1MessageByIdData, GetApiV1MessageByIdResponses, GetManageInfoData, GetManageInfoErrors, GetManageInfoResponses, MapIdentityApiConfirmEmailData, MapIdentityApiConfirmEmailResponses, PostApiV1ChannelByIdMessageData, PostApiV1ChannelByIdMessageResponses, PostApiV1ChannelData, PostApiV1ChannelResponses, PostApiV1GroupData, PostApiV1GroupResponses, PostApiV1MessageData, PostApiV1MessageResponses, PostForgotPasswordData, PostForgotPasswordErrors, PostForgotPasswordResponses, PostLoginData, PostLoginResponses, PostManage2FaData, PostManage2FaErrors, PostManage2FaResponses, PostManageInfoData, PostManageInfoErrors, PostManageInfoResponses, PostRefreshData, PostRefreshResponses, PostRegisterData, PostRegisterErrors, PostRegisterResponses, PostResendConfirmationEmailData, PostResendConfirmationEmailResponses, PostResetPasswordData, PostResetPasswordErrors, PostResetPasswordResponses, PutApiV1ChannelData, PutApiV1ChannelResponses, PutApiV1GroupData, PutApiV1GroupResponses, PutApiV1MessageData, PutApiV1MessageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postRegister = <ThrowOnError extends boolean = false>(options: Options<PostRegisterData, ThrowOnError>) => (options.client ?? client).post<PostRegisterResponses, PostRegisterErrors, ThrowOnError>({
    url: '/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postLogin = <ThrowOnError extends boolean = false>(options: Options<PostLoginData, ThrowOnError>) => (options.client ?? client).post<PostLoginResponses, unknown, ThrowOnError>({
    url: '/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postRefresh = <ThrowOnError extends boolean = false>(options: Options<PostRefreshData, ThrowOnError>) => (options.client ?? client).post<PostRefreshResponses, unknown, ThrowOnError>({
    url: '/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const mapIdentityApiConfirmEmail = <ThrowOnError extends boolean = false>(options: Options<MapIdentityApiConfirmEmailData, ThrowOnError>) => (options.client ?? client).get<MapIdentityApiConfirmEmailResponses, unknown, ThrowOnError>({ url: '/confirmEmail', ...options });

export const postResendConfirmationEmail = <ThrowOnError extends boolean = false>(options: Options<PostResendConfirmationEmailData, ThrowOnError>) => (options.client ?? client).post<PostResendConfirmationEmailResponses, unknown, ThrowOnError>({
    url: '/resendConfirmationEmail',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postForgotPassword = <ThrowOnError extends boolean = false>(options: Options<PostForgotPasswordData, ThrowOnError>) => (options.client ?? client).post<PostForgotPasswordResponses, PostForgotPasswordErrors, ThrowOnError>({
    url: '/forgotPassword',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postResetPassword = <ThrowOnError extends boolean = false>(options: Options<PostResetPasswordData, ThrowOnError>) => (options.client ?? client).post<PostResetPasswordResponses, PostResetPasswordErrors, ThrowOnError>({
    url: '/resetPassword',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postManage2Fa = <ThrowOnError extends boolean = false>(options: Options<PostManage2FaData, ThrowOnError>) => (options.client ?? client).post<PostManage2FaResponses, PostManage2FaErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/manage/2fa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getManageInfo = <ThrowOnError extends boolean = false>(options?: Options<GetManageInfoData, ThrowOnError>) => (options?.client ?? client).get<GetManageInfoResponses, GetManageInfoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/manage/info',
    ...options
});

export const postManageInfo = <ThrowOnError extends boolean = false>(options: Options<PostManageInfoData, ThrowOnError>) => (options.client ?? client).post<PostManageInfoResponses, PostManageInfoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/manage/info',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiV1Channel = <ThrowOnError extends boolean = false>(options: Options<PostApiV1ChannelData, ThrowOnError>) => (options.client ?? client).post<PostApiV1ChannelResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Channel',
    ...options,
    headers: {
        'Content-Type': 'application/json-patch+json',
        ...options.headers
    }
});

export const putApiV1Channel = <ThrowOnError extends boolean = false>(options: Options<PutApiV1ChannelData, ThrowOnError>) => (options.client ?? client).put<PutApiV1ChannelResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Channel',
    ...options,
    headers: {
        'Content-Type': 'application/json-patch+json',
        ...options.headers
    }
});

export const getApiV1ChannelByIdMessages = <ThrowOnError extends boolean = false>(options: Options<GetApiV1ChannelByIdMessagesData, ThrowOnError>) => (options.client ?? client).get<GetApiV1ChannelByIdMessagesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Channel/{id}/messages',
    ...options
});

export const postApiV1ChannelByIdMessage = <ThrowOnError extends boolean = false>(options: Options<PostApiV1ChannelByIdMessageData, ThrowOnError>) => (options.client ?? client).post<PostApiV1ChannelByIdMessageResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Channel/{id}/message',
    ...options,
    headers: {
        'Content-Type': 'application/json-patch+json',
        ...options.headers
    }
});

export const deleteApiV1ChannelById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1ChannelByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiV1ChannelByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Channel/{id}',
    ...options
});

export const getApiV1ChannelById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1ChannelByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1ChannelByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Channel/{id}',
    ...options
});

export const getApiV1GroupByIdChannels = <ThrowOnError extends boolean = false>(options: Options<GetApiV1GroupByIdChannelsData, ThrowOnError>) => (options.client ?? client).get<GetApiV1GroupByIdChannelsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Group/{id}/channels',
    ...options
});

export const getApiV1Group = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1GroupData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1GroupResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Group',
    ...options
});

export const postApiV1Group = <ThrowOnError extends boolean = false>(options: Options<PostApiV1GroupData, ThrowOnError>) => (options.client ?? client).post<PostApiV1GroupResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Group',
    ...options,
    headers: {
        'Content-Type': 'application/json-patch+json',
        ...options.headers
    }
});

export const putApiV1Group = <ThrowOnError extends boolean = false>(options: Options<PutApiV1GroupData, ThrowOnError>) => (options.client ?? client).put<PutApiV1GroupResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Group',
    ...options,
    headers: {
        'Content-Type': 'application/json-patch+json',
        ...options.headers
    }
});

export const deleteApiV1GroupById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1GroupByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiV1GroupByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Group/{id}',
    ...options
});

export const getApiV1GroupById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1GroupByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1GroupByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Group/{id}',
    ...options
});

export const postApiV1Message = <ThrowOnError extends boolean = false>(options: Options<PostApiV1MessageData, ThrowOnError>) => (options.client ?? client).post<PostApiV1MessageResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Message',
    ...options,
    headers: {
        'Content-Type': 'application/json-patch+json',
        ...options.headers
    }
});

export const putApiV1Message = <ThrowOnError extends boolean = false>(options: Options<PutApiV1MessageData, ThrowOnError>) => (options.client ?? client).put<PutApiV1MessageResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Message',
    ...options,
    headers: {
        'Content-Type': 'application/json-patch+json',
        ...options.headers
    }
});

export const deleteApiV1MessageById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiV1MessageByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiV1MessageByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Message/{id}',
    ...options
});

export const getApiV1MessageById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1MessageByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1MessageByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/Message/{id}',
    ...options
});
