// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5194/' | (string & {});
};

export type AccessTokenResponse = {
    tokenType?: null | string;
    accessToken: string;
    expiresIn: number | string;
    refreshToken: string;
};

export type ChannelDto = {
    id?: null | string;
    name: string;
    groupId: string;
    createdBy?: null | string;
};

export type CustomEmojiDto = {
    id?: null | string;
    name: string;
    groupId?: null | string;
    image?: null | string;
    authorId?: null | string;
    createdOn?: null | string;
};

export type ErrorCode = number;

export type ErrorDto = {
    error?: ErrorCode;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type GroupDto = {
    id?: null | string;
    name: string;
    createdOn?: string;
    channels?: null | Array<string>;
    groupRoles?: null | Array<string>;
};

export type GroupRoleDto = {
    id?: null | string;
    name: string;
    groupId: string;
    hierarchy: number | string;
    isDefault?: null | boolean;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type IFormFile = Blob | File;

export type InfoRequest = {
    newEmail?: null | string;
    newPassword?: null | string;
    oldPassword?: null | string;
};

export type InfoResponse = {
    email: string;
    isEmailConfirmed: boolean;
};

export type LoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: null | string;
    twoFactorRecoveryCode?: null | string;
};

export type MessageDto = {
    id?: null | string;
    currentText: string;
    authorId?: null | string;
    lastEditedOn?: null | string;
    hasBeenEdited?: null | boolean;
    isDeleted?: null | boolean;
    channelId?: null | string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type ResendConfirmationEmailRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    email: string;
    resetCode: string;
    newPassword: string;
};

export type TwoFactorRequest = {
    enable?: null | boolean;
    twoFactorCode?: null | string;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: string;
    recoveryCodesLeft: number | string;
    recoveryCodes?: null | Array<string>;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type UserDto = {
    id?: null | string;
    displayName?: null | string;
    profileImage?: null | string;
};

export type PostApiV1AuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type PostApiV1AuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostApiV1AuthRegisterError = PostApiV1AuthRegisterErrors[keyof PostApiV1AuthRegisterErrors];

export type PostApiV1AuthRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type PostApiV1AuthRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostApiV1AuthRefreshResponse = PostApiV1AuthRefreshResponses[keyof PostApiV1AuthRefreshResponses];

export type MapIdentityApiApiV1AuthConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        code: string;
        changedEmail?: string;
    };
    url: '/api/v1/auth/confirmEmail';
};

export type MapIdentityApiApiV1AuthConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/resendConfirmationEmail';
};

export type PostApiV1AuthResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgotPassword';
};

export type PostApiV1AuthForgotPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostApiV1AuthForgotPasswordError = PostApiV1AuthForgotPasswordErrors[keyof PostApiV1AuthForgotPasswordErrors];

export type PostApiV1AuthForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/resetPassword';
};

export type PostApiV1AuthResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostApiV1AuthResetPasswordError = PostApiV1AuthResetPasswordErrors[keyof PostApiV1AuthResetPasswordErrors];

export type PostApiV1AuthResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/manage/2fa';
};

export type PostApiV1AuthManage2FaErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiV1AuthManage2FaError = PostApiV1AuthManage2FaErrors[keyof PostApiV1AuthManage2FaErrors];

export type PostApiV1AuthManage2FaResponses = {
    /**
     * OK
     */
    200: TwoFactorResponse;
};

export type PostApiV1AuthManage2FaResponse = PostApiV1AuthManage2FaResponses[keyof PostApiV1AuthManage2FaResponses];

export type GetApiV1AuthManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/manage/info';
};

export type GetApiV1AuthManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiV1AuthManageInfoError = GetApiV1AuthManageInfoErrors[keyof GetApiV1AuthManageInfoErrors];

export type GetApiV1AuthManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type GetApiV1AuthManageInfoResponse = GetApiV1AuthManageInfoResponses[keyof GetApiV1AuthManageInfoResponses];

export type PostApiV1AuthManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/manage/info';
};

export type PostApiV1AuthManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiV1AuthManageInfoError = PostApiV1AuthManageInfoErrors[keyof PostApiV1AuthManageInfoErrors];

export type PostApiV1AuthManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type PostApiV1AuthManageInfoResponse = PostApiV1AuthManageInfoResponses[keyof PostApiV1AuthManageInfoResponses];

export type PostApiV1ChannelData = {
    body: ChannelDto;
    path?: never;
    query?: never;
    url: '/api/v1/Channel';
};

export type PostApiV1ChannelErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostApiV1ChannelError = PostApiV1ChannelErrors[keyof PostApiV1ChannelErrors];

export type PostApiV1ChannelResponses = {
    /**
     * Created
     */
    201: ChannelDto;
};

export type PostApiV1ChannelResponse = PostApiV1ChannelResponses[keyof PostApiV1ChannelResponses];

export type PutApiV1ChannelData = {
    body: ChannelDto;
    path?: never;
    query?: never;
    url: '/api/v1/Channel';
};

export type PutApiV1ChannelErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiV1ChannelError = PutApiV1ChannelErrors[keyof PutApiV1ChannelErrors];

export type PutApiV1ChannelResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetApiV1ChannelByIdMessagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        Take?: number | string;
        LastMessageId?: string;
    };
    url: '/api/v1/Channel/{id}/messages';
};

export type GetApiV1ChannelByIdMessagesErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1ChannelByIdMessagesError = GetApiV1ChannelByIdMessagesErrors[keyof GetApiV1ChannelByIdMessagesErrors];

export type GetApiV1ChannelByIdMessagesResponses = {
    /**
     * OK
     */
    200: Array<MessageDto>;
};

export type GetApiV1ChannelByIdMessagesResponse = GetApiV1ChannelByIdMessagesResponses[keyof GetApiV1ChannelByIdMessagesResponses];

export type PostApiV1ChannelByIdMessageData = {
    body: string;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}/message';
};

export type PostApiV1ChannelByIdMessageErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostApiV1ChannelByIdMessageError = PostApiV1ChannelByIdMessageErrors[keyof PostApiV1ChannelByIdMessageErrors];

export type PostApiV1ChannelByIdMessageResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type PostApiV1ChannelByIdMessageResponse = PostApiV1ChannelByIdMessageResponses[keyof PostApiV1ChannelByIdMessageResponses];

export type DeleteApiV1ChannelByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}';
};

export type DeleteApiV1ChannelByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiV1ChannelByIdError = DeleteApiV1ChannelByIdErrors[keyof DeleteApiV1ChannelByIdErrors];

export type DeleteApiV1ChannelByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetApiV1ChannelByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}';
};

export type GetApiV1ChannelByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1ChannelByIdError = GetApiV1ChannelByIdErrors[keyof GetApiV1ChannelByIdErrors];

export type GetApiV1ChannelByIdResponses = {
    /**
     * OK
     */
    200: ChannelDto;
};

export type GetApiV1ChannelByIdResponse = GetApiV1ChannelByIdResponses[keyof GetApiV1ChannelByIdResponses];

export type PostApiV1CustomEmojiData = {
    body: {
        Name?: string;
        File?: IFormFile;
        GroupId?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/CustomEmoji';
};

export type PostApiV1CustomEmojiErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostApiV1CustomEmojiError = PostApiV1CustomEmojiErrors[keyof PostApiV1CustomEmojiErrors];

export type PostApiV1CustomEmojiResponses = {
    /**
     * OK
     */
    200: CustomEmojiDto;
};

export type PostApiV1CustomEmojiResponse = PostApiV1CustomEmojiResponses[keyof PostApiV1CustomEmojiResponses];

export type PutApiV1CustomEmojiData = {
    body: CustomEmojiDto;
    path?: never;
    query?: never;
    url: '/api/v1/CustomEmoji';
};

export type PutApiV1CustomEmojiErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiV1CustomEmojiError = PutApiV1CustomEmojiErrors[keyof PutApiV1CustomEmojiErrors];

export type PutApiV1CustomEmojiResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type DeleteApiV1CustomEmojiByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/CustomEmoji/{id}';
};

export type DeleteApiV1CustomEmojiByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiV1CustomEmojiByIdError = DeleteApiV1CustomEmojiByIdErrors[keyof DeleteApiV1CustomEmojiByIdErrors];

export type DeleteApiV1CustomEmojiByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetApiV1CustomEmojiByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/CustomEmoji/{id}';
};

export type GetApiV1CustomEmojiByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1CustomEmojiByIdError = GetApiV1CustomEmojiByIdErrors[keyof GetApiV1CustomEmojiByIdErrors];

export type GetApiV1CustomEmojiByIdResponses = {
    /**
     * OK
     */
    200: CustomEmojiDto;
};

export type GetApiV1CustomEmojiByIdResponse = GetApiV1CustomEmojiByIdResponses[keyof GetApiV1CustomEmojiByIdResponses];

export type GetApiV1DownloadByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Download/{id}';
};

export type GetApiV1DownloadByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1DownloadByIdError = GetApiV1DownloadByIdErrors[keyof GetApiV1DownloadByIdErrors];

export type GetApiV1GroupByIdRolesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}/roles';
};

export type GetApiV1GroupByIdRolesErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1GroupByIdRolesError = GetApiV1GroupByIdRolesErrors[keyof GetApiV1GroupByIdRolesErrors];

export type GetApiV1GroupByIdRolesResponses = {
    /**
     * OK
     */
    200: Array<GroupRoleDto>;
};

export type GetApiV1GroupByIdRolesResponse = GetApiV1GroupByIdRolesResponses[keyof GetApiV1GroupByIdRolesResponses];

export type GetApiV1GroupByIdChannelsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}/channels';
};

export type GetApiV1GroupByIdChannelsErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1GroupByIdChannelsError = GetApiV1GroupByIdChannelsErrors[keyof GetApiV1GroupByIdChannelsErrors];

export type GetApiV1GroupByIdChannelsResponses = {
    /**
     * OK
     */
    200: Array<ChannelDto>;
};

export type GetApiV1GroupByIdChannelsResponse = GetApiV1GroupByIdChannelsResponses[keyof GetApiV1GroupByIdChannelsResponses];

export type GetApiV1GroupByIdEmojiData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}/emoji';
};

export type GetApiV1GroupByIdEmojiErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1GroupByIdEmojiError = GetApiV1GroupByIdEmojiErrors[keyof GetApiV1GroupByIdEmojiErrors];

export type GetApiV1GroupByIdEmojiResponses = {
    /**
     * OK
     */
    200: Array<CustomEmojiDto>;
};

export type GetApiV1GroupByIdEmojiResponse = GetApiV1GroupByIdEmojiResponses[keyof GetApiV1GroupByIdEmojiResponses];

export type GetApiV1GroupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type GetApiV1GroupErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1GroupError = GetApiV1GroupErrors[keyof GetApiV1GroupErrors];

export type GetApiV1GroupResponses = {
    /**
     * OK
     */
    200: Array<GroupDto>;
};

export type GetApiV1GroupResponse = GetApiV1GroupResponses[keyof GetApiV1GroupResponses];

export type PostApiV1GroupData = {
    body: GroupDto;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type PostApiV1GroupErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostApiV1GroupError = PostApiV1GroupErrors[keyof PostApiV1GroupErrors];

export type PostApiV1GroupResponses = {
    /**
     * Created
     */
    201: GroupDto;
};

export type PostApiV1GroupResponse = PostApiV1GroupResponses[keyof PostApiV1GroupResponses];

export type PutApiV1GroupData = {
    body: GroupDto;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type PutApiV1GroupErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiV1GroupError = PutApiV1GroupErrors[keyof PutApiV1GroupErrors];

export type PutApiV1GroupResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type DeleteApiV1GroupByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}';
};

export type DeleteApiV1GroupByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiV1GroupByIdError = DeleteApiV1GroupByIdErrors[keyof DeleteApiV1GroupByIdErrors];

export type DeleteApiV1GroupByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetApiV1GroupByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}';
};

export type GetApiV1GroupByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1GroupByIdError = GetApiV1GroupByIdErrors[keyof GetApiV1GroupByIdErrors];

export type GetApiV1GroupByIdResponses = {
    /**
     * OK
     */
    200: GroupDto;
};

export type GetApiV1GroupByIdResponse = GetApiV1GroupByIdResponses[keyof GetApiV1GroupByIdResponses];

export type PostApiV1GroupRoleData = {
    body: GroupRoleDto;
    path?: never;
    query?: never;
    url: '/api/v1/GroupRole';
};

export type PostApiV1GroupRoleErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostApiV1GroupRoleError = PostApiV1GroupRoleErrors[keyof PostApiV1GroupRoleErrors];

export type PostApiV1GroupRoleResponses = {
    /**
     * Created
     */
    201: GroupRoleDto;
};

export type PostApiV1GroupRoleResponse = PostApiV1GroupRoleResponses[keyof PostApiV1GroupRoleResponses];

export type PutApiV1GroupRoleData = {
    body: GroupRoleDto;
    path?: never;
    query?: never;
    url: '/api/v1/GroupRole';
};

export type PutApiV1GroupRoleErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiV1GroupRoleError = PutApiV1GroupRoleErrors[keyof PutApiV1GroupRoleErrors];

export type PutApiV1GroupRoleResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type DeleteApiV1GroupRoleByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/GroupRole/{id}';
};

export type DeleteApiV1GroupRoleByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiV1GroupRoleByIdError = DeleteApiV1GroupRoleByIdErrors[keyof DeleteApiV1GroupRoleByIdErrors];

export type DeleteApiV1GroupRoleByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetApiV1GroupRoleByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/GroupRole/{id}';
};

export type GetApiV1GroupRoleByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1GroupRoleByIdError = GetApiV1GroupRoleByIdErrors[keyof GetApiV1GroupRoleByIdErrors];

export type GetApiV1GroupRoleByIdResponses = {
    /**
     * OK
     */
    200: GroupRoleDto;
};

export type GetApiV1GroupRoleByIdResponse = GetApiV1GroupRoleByIdResponses[keyof GetApiV1GroupRoleByIdResponses];

export type PostApiV1MessageData = {
    body: MessageDto;
    path?: never;
    query?: never;
    url: '/api/v1/Message';
};

export type PostApiV1MessageErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostApiV1MessageError = PostApiV1MessageErrors[keyof PostApiV1MessageErrors];

export type PostApiV1MessageResponses = {
    /**
     * Created
     */
    201: MessageDto;
};

export type PostApiV1MessageResponse = PostApiV1MessageResponses[keyof PostApiV1MessageResponses];

export type PutApiV1MessageData = {
    body: MessageDto;
    path?: never;
    query?: never;
    url: '/api/v1/Message';
};

export type PutApiV1MessageErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutApiV1MessageError = PutApiV1MessageErrors[keyof PutApiV1MessageErrors];

export type PutApiV1MessageResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type DeleteApiV1MessageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Message/{id}';
};

export type DeleteApiV1MessageByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiV1MessageByIdError = DeleteApiV1MessageByIdErrors[keyof DeleteApiV1MessageByIdErrors];

export type DeleteApiV1MessageByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetApiV1MessageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Message/{id}';
};

export type GetApiV1MessageByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1MessageByIdError = GetApiV1MessageByIdErrors[keyof GetApiV1MessageByIdErrors];

export type GetApiV1MessageByIdResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type GetApiV1MessageByIdResponse = GetApiV1MessageByIdResponses[keyof GetApiV1MessageByIdResponses];

export type GetApiV1UserByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/User/{id}';
};

export type GetApiV1UserByIdErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1UserByIdError = GetApiV1UserByIdErrors[keyof GetApiV1UserByIdErrors];

export type GetApiV1UserByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetApiV1UserByIdResponse = GetApiV1UserByIdResponses[keyof GetApiV1UserByIdResponses];

export type GetApiV1UserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/User/me';
};

export type GetApiV1UserMeErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiV1UserMeError = GetApiV1UserMeErrors[keyof GetApiV1UserMeErrors];

export type GetApiV1UserMeResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetApiV1UserMeResponse = GetApiV1UserMeResponses[keyof GetApiV1UserMeResponses];

export type PostApiV1UserProfileImageData = {
    body: {
        ContentType?: string;
        ContentDisposition?: string;
        Headers?: {
            [key: string]: Array<string>;
        };
        Length?: number | string;
        Name?: string;
        FileName?: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/User/profile-image';
};

export type PostApiV1UserProfileImageErrors = {
    /**
     * Bad Request
     */
    400: ErrorDto;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostApiV1UserProfileImageError = PostApiV1UserProfileImageErrors[keyof PostApiV1UserProfileImageErrors];
