// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5194/' | (string & {});
};

export type AccessTokenResponse = {
    tokenType?: null | string;
    accessToken: string;
    expiresIn: number | string;
    refreshToken: string;
};

export type ChannelDto = {
    id?: null | string;
    name: string;
    groupId: string;
    createdBy?: null | string;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type GroupDto = {
    id?: null | string;
    name: string;
    createdOn?: string;
    channels?: null | Array<string>;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type InfoRequest = {
    newEmail?: null | string;
    newPassword?: null | string;
    oldPassword?: null | string;
};

export type InfoResponse = {
    email: string;
    isEmailConfirmed: boolean;
};

export type LoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: null | string;
    twoFactorRecoveryCode?: null | string;
};

export type MessageDto = {
    id?: null | string;
    currentText: string;
    authorId?: null | string;
    createdOn?: null | string;
    lastEditedOn?: null | string;
    hasBeenEdited?: null | boolean;
    isDeleted?: null | boolean;
    channelId?: null | string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type ResendConfirmationEmailRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    email: string;
    resetCode: string;
    newPassword: string;
};

export type TwoFactorRequest = {
    enable?: null | boolean;
    twoFactorCode?: null | string;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: string;
    recoveryCodesLeft: number | string;
    recoveryCodes?: null | Array<string>;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type PostApiV1AuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type PostApiV1AuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostApiV1AuthRegisterError = PostApiV1AuthRegisterErrors[keyof PostApiV1AuthRegisterErrors];

export type PostApiV1AuthRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/api/v1/auth/login';
};

export type PostApiV1AuthLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostApiV1AuthLoginResponse = PostApiV1AuthLoginResponses[keyof PostApiV1AuthLoginResponses];

export type PostApiV1AuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type PostApiV1AuthRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostApiV1AuthRefreshResponse = PostApiV1AuthRefreshResponses[keyof PostApiV1AuthRefreshResponses];

export type MapIdentityApiApiV1AuthConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        code: string;
        changedEmail?: string;
    };
    url: '/api/v1/auth/confirmEmail';
};

export type MapIdentityApiApiV1AuthConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/resendConfirmationEmail';
};

export type PostApiV1AuthResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/forgotPassword';
};

export type PostApiV1AuthForgotPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostApiV1AuthForgotPasswordError = PostApiV1AuthForgotPasswordErrors[keyof PostApiV1AuthForgotPasswordErrors];

export type PostApiV1AuthForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/resetPassword';
};

export type PostApiV1AuthResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostApiV1AuthResetPasswordError = PostApiV1AuthResetPasswordErrors[keyof PostApiV1AuthResetPasswordErrors];

export type PostApiV1AuthResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiV1AuthManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/manage/2fa';
};

export type PostApiV1AuthManage2FaErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiV1AuthManage2FaError = PostApiV1AuthManage2FaErrors[keyof PostApiV1AuthManage2FaErrors];

export type PostApiV1AuthManage2FaResponses = {
    /**
     * OK
     */
    200: TwoFactorResponse;
};

export type PostApiV1AuthManage2FaResponse = PostApiV1AuthManage2FaResponses[keyof PostApiV1AuthManage2FaResponses];

export type GetApiV1AuthManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/manage/info';
};

export type GetApiV1AuthManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiV1AuthManageInfoError = GetApiV1AuthManageInfoErrors[keyof GetApiV1AuthManageInfoErrors];

export type GetApiV1AuthManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type GetApiV1AuthManageInfoResponse = GetApiV1AuthManageInfoResponses[keyof GetApiV1AuthManageInfoResponses];

export type PostApiV1AuthManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/manage/info';
};

export type PostApiV1AuthManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiV1AuthManageInfoError = PostApiV1AuthManageInfoErrors[keyof PostApiV1AuthManageInfoErrors];

export type PostApiV1AuthManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type PostApiV1AuthManageInfoResponse = PostApiV1AuthManageInfoResponses[keyof PostApiV1AuthManageInfoResponses];

export type PostApiV1ChannelData = {
    body: ChannelDto;
    path?: never;
    query?: never;
    url: '/api/v1/Channel';
};

export type PostApiV1ChannelResponses = {
    /**
     * OK
     */
    200: ChannelDto;
};

export type PostApiV1ChannelResponse = PostApiV1ChannelResponses[keyof PostApiV1ChannelResponses];

export type PutApiV1ChannelData = {
    body: ChannelDto;
    path?: never;
    query?: never;
    url: '/api/v1/Channel';
};

export type PutApiV1ChannelResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ChannelByIdMessagesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        Take?: number | string;
        LastMessageId?: string;
    };
    url: '/api/v1/Channel/{id}/messages';
};

export type GetApiV1ChannelByIdMessagesResponses = {
    /**
     * OK
     */
    200: Array<MessageDto>;
};

export type GetApiV1ChannelByIdMessagesResponse = GetApiV1ChannelByIdMessagesResponses[keyof GetApiV1ChannelByIdMessagesResponses];

export type PostApiV1ChannelByIdMessageData = {
    body: string;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}/message';
};

export type PostApiV1ChannelByIdMessageResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type PostApiV1ChannelByIdMessageResponse = PostApiV1ChannelByIdMessageResponses[keyof PostApiV1ChannelByIdMessageResponses];

export type DeleteApiV1ChannelByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}';
};

export type DeleteApiV1ChannelByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1ChannelByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Channel/{id}';
};

export type GetApiV1ChannelByIdResponses = {
    /**
     * OK
     */
    200: ChannelDto;
};

export type GetApiV1ChannelByIdResponse = GetApiV1ChannelByIdResponses[keyof GetApiV1ChannelByIdResponses];

export type GetApiV1GroupByIdChannelsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}/channels';
};

export type GetApiV1GroupByIdChannelsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1GroupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type GetApiV1GroupResponses = {
    /**
     * OK
     */
    200: Array<GroupDto>;
};

export type GetApiV1GroupResponse = GetApiV1GroupResponses[keyof GetApiV1GroupResponses];

export type PostApiV1GroupData = {
    body: GroupDto;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type PostApiV1GroupResponses = {
    /**
     * OK
     */
    200: GroupDto;
};

export type PostApiV1GroupResponse = PostApiV1GroupResponses[keyof PostApiV1GroupResponses];

export type PutApiV1GroupData = {
    body: GroupDto;
    path?: never;
    query?: never;
    url: '/api/v1/Group';
};

export type PutApiV1GroupResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1GroupByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}';
};

export type DeleteApiV1GroupByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1GroupByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Group/{id}';
};

export type GetApiV1GroupByIdResponses = {
    /**
     * OK
     */
    200: GroupDto;
};

export type GetApiV1GroupByIdResponse = GetApiV1GroupByIdResponses[keyof GetApiV1GroupByIdResponses];

export type PostApiV1MessageData = {
    body: MessageDto;
    path?: never;
    query?: never;
    url: '/api/v1/Message';
};

export type PostApiV1MessageResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type PostApiV1MessageResponse = PostApiV1MessageResponses[keyof PostApiV1MessageResponses];

export type PutApiV1MessageData = {
    body: MessageDto;
    path?: never;
    query?: never;
    url: '/api/v1/Message';
};

export type PutApiV1MessageResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiV1MessageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Message/{id}';
};

export type DeleteApiV1MessageByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiV1MessageByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/Message/{id}';
};

export type GetApiV1MessageByIdResponses = {
    /**
     * OK
     */
    200: MessageDto;
};

export type GetApiV1MessageByIdResponse = GetApiV1MessageByIdResponses[keyof GetApiV1MessageByIdResponses];
